AWSTemplateFormatVersion: '2010-09-09'
Description: 'Agentic Profile MCP Lambda Function - SAM Template'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues: [dev, staging, prod]

Resources:
  # Lambda Function
  AgenticProfileMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'agentic-profile-mcp-${Environment}'
      CodeUri: ./
      Handler: dist/index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          NODE_ENV: !Ref Environment
      Timeout: 30
      MemorySize: 256
      Tags:
        Environment: !Ref Environment
        Service: agentic-profile-mcp
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/agentic-profile-mcp-${Environment}'
      RetentionInDays: 14

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayUrl'

  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt AgenticProfileMCPFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'

  LambdaFunctionName:
    Description: 'Lambda Function Name'
    Value: !Ref AgenticProfileMCPFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName' 